Techs
wolox-training/ma-react pull request #4
Opened 2018-08-06 17:36 UTC by aatar

Summary: Added the tech square design
Card: https://trello.com/c/sl1qLlrM/22-tecnologia
Screen:
![screenshot from 2018-08-06 14-34-48](https://user-images.githubusercontent.com/23110203/43731799-0d31d492-9986-11e8-852a-c195f253cfe2.png)

2018-08-08 16:23 UTC, SKOLZ requested changes

2018-08-08 16:23 UTC, SKOLZ commented on index.html
> +
remove all unnecesary empty lines from here

2018-08-08 16:23 UTC, SKOLZ commented on index.html
> +        <span class="tech-description">React is a declarative, component-based JavaScript library for building user interfaces.</span>
this should be a `p` tag instead of a `span` since it shows a paregraph.

2018-08-08 16:23 UTC, SKOLZ commented on index.html
> +        <span class="tech-title">React JS</span>
this should be a headline tag (with less hierarchy than h1) instead of a `span` since it shows a title.

2018-08-08 16:23 UTC, SKOLZ commented on index.html
> +      <div class="tech-container-content">
you should be able to remove this div

2018-08-08 16:23 UTC, SKOLZ commented on index.html
> +  <div class="techs-container">
delete this for now, we'll add it in the next pr when the layout creation is applied

2018-08-08 16:23 UTC, SKOLZ commented on scss/tech.scss
> +.techs-container {
delete this

2018-08-08 16:23 UTC, SKOLZ commented on scss/tech.scss
> +.tech-container-content {
I think this should be deleted and the styles should be moved to `.tech-container`

2018-08-08 16:23 UTC, SKOLZ commented on scss/tech.scss
> +  padding-left: 15px;
I'd remove this line

2018-08-08 16:23 UTC, SKOLZ commented on scss/tech.scss
> +  margin-left: 25px;
I'd remove this line

2018-08-08 16:23 UTC, SKOLZ commented on scss/tech.scss
> +  padding-top: 20px;
I'd remove this line

2018-08-08 16:23 UTC, SKOLZ commented on scss/tech.scss
> +  top: 100px;
I'd remove this line

2018-08-08 16:23 UTC, SKOLZ commented on scss/tech.scss
> +    height: 350px;
I'd use 100%

2018-08-08 16:23 UTC, SKOLZ commented on scss/tech.scss
> +    width: 260px;
I'd use 100%

2018-08-08 16:23 UTC, SKOLZ commented on scss/tech.scss
> +    left: 0;
I'd use negative values to move the border away from the green box

2018-08-08 16:23 UTC, SKOLZ commented on scss/tech.scss
> +    top: 0;
I'd use negative values to move the border away from the green box

2018-08-08 16:23 UTC, SKOLZ commented on scss/tech.scss
> +  &::before {
I think this should be done using an image tag. the image is part of the content that we would like to show in the view if there's no css. since it's part of the `tech model`

2018-08-08 16:23 UTC, SKOLZ commented on scss/tech.scss
> +    padding-top: 20px;
padding should be in the parent and margin between siblings. please read this post to have a better view of it https://medium.com/wolox-driving-innovation/what-margin-padding-taught-me-after-50-projects-6878b53c903f

2018-08-08 16:23 UTC, SKOLZ commented on scss/tech.scss
> +    padding-top: 10px;
you need margin here instead, and preferably only in the bottom

2018-08-08 16:23 UTC, SKOLZ commented on scss/tech.scss
> +    padding: 30px 10px;
you need margin here instead, and preferably only in the bottom

2018-08-08 16:23 UTC, SKOLZ commented on scss/titles.scss
> +  left: 100px;
no need

2018-08-08 16:23 UTC, SKOLZ commented on scss/titles.scss
> +  margin-bottom: 50px;
we'll do this later, delete it for now

2018-08-08 16:23 UTC, SKOLZ commented on scss/titles.scss
> +  margin-top: 150px;
we'll do this later, delete it for now

2018-08-08 17:08 UTC, aatar commented on index.html
> +      <div class="tech-container-content">
which one of the three divs?

2018-08-08 17:35 UTC, SKOLZ requested changes

2018-08-08 17:35 UTC, SKOLZ commented on index.html
> +    <div class="tech-container-content">
delete this div, leave the  content inside of the `tech-container` div. also add the image by using an image tag here

2018-08-08 19:42 UTC, SKOLZ requested changes

2018-08-08 19:42 UTC, SKOLZ commented on index.html
> +    <p class="tech-release">Release: 2013</p>
this should be a `span` since it's a small piece of text.

2018-08-08 19:42 UTC, SKOLZ commented on scss/tech.scss
> +    position: relative;
this should be absolute positioned, while the position of the content of the tech (title, logo, etc) should not be altered

2018-08-08 19:42 UTC, SKOLZ commented on scss/tech.scss
> +.tech-container {
this should have position relative

2018-08-08 19:42 UTC, SKOLZ commented on scss/tech.scss
> +    position: relative;
not needed

2018-08-08 19:42 UTC, SKOLZ commented on scss/tech.scss
> +    top: 10px;
this should be handled through padding in the parent instead of doing it this way.

2018-08-08 19:42 UTC, SKOLZ commented on scss/tech.scss
> +    margin-top: 20px;
margin-bottom is always preferred over top because it makes the html easier to read

2018-08-08 19:42 UTC, SKOLZ commented on scss/tech.scss
> +    margin: 30px 10px;
being the last element you don't need margin at the bottom, that should be handled through padding in the container. and the top margin should be handled with bottom-margin in the element above this one.

2018-08-08 19:42 UTC, SKOLZ commented on scss/tech.scss
> +    margin: 30px 10px;
you don't need margins at the sides, those should be handled with padding in the parent.

2018-08-08 19:42 UTC, SKOLZ commented on scss/tech.scss
> +    margin-top: 0;
remove this.

2018-08-08 20:13 UTC, SKOLZ requested changes

2018-08-08 20:13 UTC, SKOLZ commented on scss/tech.scss
> +  padding-bottom: 30px;
you can group all paddings by doing `padding: 10px 10px 30px;`

2018-08-08 20:13 UTC, SKOLZ commented on scss/tech.scss
> +    left: 0;
not needed

2018-08-08 20:13 UTC, SKOLZ commented on scss/tech.scss
> +    margin-bottom: 20px;
.tech-description shouldn't add a margin in the bottom

2018-08-08 20:13 UTC, SKOLZ commented on scss/tech.scss
> +    margin-bottom: 30px;
you are already adding a margin bottom in line 35

2018-08-08 20:13 UTC, SKOLZ commented on scss/tech.scss
> +    margin: 30px 10px;
you are already adding a margin bottom in line 35

2018-08-10 15:01 UTC, SKOLZ approved these changes

2018-08-10 16:52 UTC, merged